repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 4924b0e01e032fea073ad04a1c5cfa7e4add0afb  # v0.15.6
    hooks:
      - id: ruff
        args: [--fix, --config=ruff.toml]
      - id: ruff-format
        args: [--config=ruff.toml]
